data:
  path: data/cs-training.csv
  target: SeriousDlqin2yrs

decision:
  threshold: 0.05
  strategy: max_recall_default

train:
  test_size: 0.2
  random_state: 42

model:
  type: logistic_regression
  params:
    C: 1.0
    max_iter: 1000

mlflow:
  experiment_name: credit-default-train
  model_name: credit-default-model
  # fallback si MODEL_URI n'est pas fourni en env var
  model_uri: models:/credit-default-model/Production

